<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Title>$(AssemblyName)</Title>
    <Version>1.0.71.26231</Version>
    <Description>An easily implementable, modular and customizable way to call an API with.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/Codespirals/Codespirals.Solutions.ApiCaller</RepositoryUrl>
    <PackageTags>codespirals; api; </PackageTags>
    <PackageOutputPath>$(OneDrive)\NuGet</PackageOutputPath>
    <NeutralLanguage>en</NeutralLanguage>
    <PackageLicenseExpression>CC0-1.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>False</PackageRequireLicenseAcceptance>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>codespirals</Authors>
    <Copyright>$(Company)</Copyright>
    <PackageIcon>logo.png</PackageIcon>
    <PackageProjectUrl>https://codespirals.dev/</PackageProjectUrl>
    <Company>codespirals</Company>
    <RunPostBuildEvent>OnOutputUpdated</RunPostBuildEvent>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <SignAssembly>False</SignAssembly>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <NoWarn>1701;1702;IDE0130;</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\Images\icon.png" />
    <None Remove="Resources\Images\logo.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Codespirals.Base.Shared" Version="1.1.2.26120" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\Images\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </Resource>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Codespirals.Base" />
  </ItemGroup>
  <ItemGroup>
    <None Update="AutoUpdateVersionNumber.ps1">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Tests\" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="PowerShell -ExecutionPolicy Bypass -NoProfile -File AutoUpdateVersionNumber.ps1" />
  </Target>
</Project>