<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>codespirals</Authors>
    <Company>codespirals</Company>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Codespirals.Solutions.ApiCaller" Version="0.4.84.25212" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ExampleText.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ExampleText.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\ExampleText.resx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>ExampleText.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>
